name: Build and Deploy Wasm

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build Wasm
        run: wasm-pack build --target web

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wasm-build
          path: pkg/
